services:
  mariadb:
    image: mariadb:11.1
    container_name: maria_database
    environment:
      - MARIADB_ROOT_PASSWORD=ilovejava
      - MARIADB_DATABASE=andrelson
      - MARIADB_USER=javauser
      - MARIADB_PASSWORD=ilovejava
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: