version: '3.8'

services:

  springboot-app:
    build: .
    container_name: the-system
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/wedsan-database
      SPRING_DATASOURCE_USERNAME: wedsan
      SPRING_DATASOURCE_PASSWORD: security-password
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    image: mariadb:10.5
    container_name: mariadb-ctn
    environment:
      MARIADB_USER: wedsan
      MARIADB_PASSWORD: security-password
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: wedsan-database
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
